//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SQH.Domain.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Content
    {
        public Content()
        {
            this.MetaDatas = new HashSet<MetaData>();
        }
    
        public int ContentId { get; set; }
        public string TopicHeadline { get; set; }
        public string Description { get; set; }
        public int SourceId { get; set; }
        public Nullable<int> CategoryId { get; set; }
    
        public virtual Category Category { get; set; }
        public virtual Source Source { get; set; }
        public virtual ICollection<MetaData> MetaDatas { get; set; }
    }
}
