//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SQH.Domain.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class MetaData
    {
        public int MetaDataId { get; set; }
        public string Name { get; set; }
        public string Value { get; set; }
        public int ContentId { get; set; }
    
        public virtual Content Content { get; set; }
    }
}
